import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Terms of Service | Financial Planner AI",
  description: "Financial Planner AI terms of service, effective January 1, 2025",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <main className="container mx-auto px-4 py-12 max-w-4xl">
        <article className="prose prose-gray dark:prose-invert max-w-none">
          <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>

          <div className="text-sm text-muted-foreground mb-8">Effective: January 1, 2025</div>

          {/* Important Notice Box */}
          <div className="bg-muted p-6 rounded-lg mb-8">
            <strong className="text-lg block mb-3">IMPORTANT NOTICE REGARDING YOUR LEGAL RIGHTS</strong>
            <p className="text-base">
              PLEASE READ THESE TERMS OF SERVICE CAREFULLY. THEY CONTAIN AN ARBITRATION AGREEMENT AND CLASS ACTION
              WAIVER THAT AFFECT YOUR LEGAL RIGHTS.
            </p>
          </div>

          <p className="text-base mb-8">
            By accessing or using the Services provided by Financial Planner AI, LLC, you acknowledge that you have
            read, understood, and agree to be bound by these Terms of Service, including the binding arbitration
            provision and class action waiver found in Section 12.
          </p>

          {/* Section 1 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-1">
              1. INTRODUCTION AND ACCEPTANCE
            </h2>
            <p className="text-base mb-4">
              Welcome to Financial Planner AI. These Terms of Service (the &quot;Terms&quot;) constitute a legally
              binding agreement between you and Financial Planner AI, LLC, a limited liability company organized under
              the laws of New Jersey (&quot;Financial Planner AI,&quot; &quot;we,&quot; &quot;our,&quot; or
              &quot;us&quot;). These Terms govern your access to and use of our website located at{" "}
              <Link href="https://www.lifeinsuranceplanner-ai.com" className="text-primary hover:underline">
                https://www.lifeinsuranceplanner-ai.com
              </Link>{" "}
              (the &quot;Website&quot;), our proprietary web-based software application (the &quot;Application&quot;),
              our AI-powered analysis feature (&quot;Insurance Planner AI&quot;), our chatbot service, and all related
              services (collectively, the &quot;Services&quot;).
            </p>
            <p className="text-base mb-4">
              These Terms incorporate by reference our Privacy Policy, available at{" "}
              <Link href="https://www.lifeinsuranceplanner-ai.com/privacy" className="text-primary hover:underline">
                https://www.lifeinsuranceplanner-ai.com/privacy
              </Link>
              , our Cookie Policy{" "}
              <Link
                href="https://www.lifeinsuranceplanner-ai.com/cookie-policy"
                className="text-primary hover:underline"
              >
                https://www.lifeinsuranceplanner-ai.com/cookie-policy
              </Link>{" "}
              and any additional terms, conditions, or policies we may provide to you from time to time.
            </p>
            <p className="text-base mb-4">
              By accessing or using our Services, you represent and warrant that you have read, understood, and agree to
              be bound by these Terms. If you don&apos;t agree to these Terms in their entirety, you must not access or
              use our Services.
            </p>
          </section>

          {/* Section 2 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-2">
              2. DEFINITIONS AND INTERPRETATION
            </h2>
            <h3 className="text-xl font-medium mb-3">2.1 Throughout these Terms, the following definitions apply:</h3>
            <p className="text-base mb-4">
              &quot;Affiliate&quot; means any entity that directly or indirectly controls, is controlled by, or is under
              common control with Financial Planner AI, where &quot;control&quot; means the ownership of, or the power
              to vote, at least fifty percent (50%) of the voting stock, shares or interests of such entity.
            </p>
            <p className="text-base mb-4">
              &quot;AI Technology&quot; means our artificial intelligence and machine learning technologies, algorithms,
              models, and systems used to provide the Services.
            </p>
            <p className="text-base mb-4">
              &quot;Analyses&quot; means the outputs, reports, summaries, and other materials generated by our AI
              Technology based on the information and documentation you provide.
            </p>
            {/* ... continued definitions ... */}
            <h3 className="text-xl font-medium mb-3">2.2 In these Terms:</h3>
            <p className="text-base mb-4">
              (a) the words &quot;include,&quot; &quot;includes,&quot; and &quot;including&quot; are deemed to be
              followed by the words &quot;without limitation&quot;;
              <br />
              (b) the word &quot;or&quot; is not exclusive;
              <br />
              (c) the words &quot;herein,&quot; &quot;hereof,&quot; &quot;hereby,&quot; &quot;hereto,&quot; and
              &quot;hereunder&quot; refer to these Terms as a whole; and
              <br />
              (d) words denoting the singular have a comparable meaning when used in the plural, and vice-versa.
            </p>
          </section>

          {/* Section 3 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-3">
              3. ELIGIBILITY AND REGISTRATION
            </h2>
            <h3 className="text-xl font-medium mb-3">3.1 Eligibility Requirements</h3>
            <p className="text-base mb-4">
              To access and use our Services, you must be at least eighteen (18) years old and have the legal capacity
              to form a binding contract with Financial Planner AI under applicable law.
            </p>
            {/* ... continued section 3 content ... */}
            <h3 className="text-xl font-medium mb-3">3.2 Registration Process</h3>
            <p className="text-base mb-4">
              To access certain features of our Services, you must register for an account. When registering, you agree
              to provide accurate, current, and complete information about yourself as prompted by our registration
              process.
            </p>
            <h3 className="text-xl font-medium mb-3">3.3 Account Security</h3>
            <p className="text-base mb-4">
              You are responsible for maintaining the confidentiality of your account credentials, including your
              username and password. You agree to notify us immediately of any unauthorized use of your account or any
              other breach of security.
            </p>
            <h3 className="text-xl font-medium mb-3">3.4 Account Types</h3>
            <p className="text-base mb-4">
              Our Services may offer different types of accounts with varying features and functionality. The specific
              features and functionality available to you will depend on the type of account you register for and
              maintain.
            </p>
          </section>

          {/* Section 4 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-4">
              4. SERVICE DESCRIPTION AND SCOPE
            </h2>
            <h3 className="text-xl font-medium mb-3">4.1 Core Services</h3>
            <p className="text-base mb-4">
              Financial Planner AI provides a web-based software application that enables Life Insurance Policy Owners
              to conduct life insurance policy analyses through our proprietary AI Technology.
            </p>
            <h3 className="text-xl font-medium mb-3">4.2 Service Delivery</h3>
            <p className="text-base mb-4">
              We will make the Services available to you pursuant to these Terms and any applicable Documentation. We
              may modify, enhance, or otherwise change the Services at any time in our sole discretion.
            </p>
            <h3 className="text-xl font-medium mb-3">4.3 Service Access</h3>
            <p className="text-base mb-4">
              Subject to your compliance with these Terms and payment of applicable fees, we grant you a limited,
              non-exclusive, non-transferable, non-sublicensable right to access and use the Services solely for your
              internal business or personal purposes during the term of these Terms.
            </p>
          </section>

          {/* Section 5 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-5">
              5. CRITICAL LIMITATIONS AND DISCLAIMERS
            </h2>
            <h3 className="text-xl font-medium mb-3">5.1 No Professional Advice</h3>
            <p className="text-base mb-4">
              YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT THE SERVICES DO NOT CONSTITUTE PROFESSIONAL ADVICE OF ANY KIND.
              The Services are informational tools only and are not intended to replace the advice or services of
              licensed professionals. Financial Planner AI does not provide tax, legal, financial, insurance, or
              investment advice. We do not recommend, endorse, or sell any insurance products, policies, or companies.
            </p>
            <p className="text-base mb-4">
              You must consult with qualified Professional Advisors before making any decisions about your life
              insurance policy or taking any actions based on information provided through our Services. The Analyses
              generated by our Services are intended solely as starting points for discussions with your Professional
              Advisors and should never be relied upon as the sole basis for any decision or action regarding your life
              insurance policy.
            </p>

            <h3 className="text-xl font-medium mb-3">5.2 AI Technology Limitations</h3>
            <p className="text-base mb-4">
              You expressly acknowledge and understand that our Services utilize automated artificial intelligence and
              machine learning technologies that have inherent limitations and potential for error. The accuracy and
              reliability of our Analyses depend entirely on the quality, completeness, and accuracy of the information
              and documentation you provide.
            </p>
            <p className="text-base mb-4">Our AI Technology:</p>
            <p className="text-base mb-4">
              (a) May contain errors, bugs, or inaccuracies;
              <br />
              (b) May not capture all relevant factors or considerations;
              <br />
              (c) May produce inconsistent or unexpected results;
              <br />
              (d) Requires human review and professional verification;
              <br />
              (e) Is subject to regular updates that may affect results;
              <br />
              (f) Cannot verify the completeness or accuracy of input data;
              <br />
              (g) May have biases or limitations we have not identified; and
              <br />
              (h) Should never be relied upon without independent verification.
            </p>

            <h3 className="text-xl font-medium mb-3">5.3 Document Processing Restrictions</h3>
            <p className="text-base mb-4">
              The Services are designed to process only life insurance policy illustrations. We do not analyze other
              insurance or financial documents. You acknowledge and agree that:
            </p>
            <p className="text-base mb-4">
              (a) We cannot verify the completeness, accuracy, or authenticity of any illustration you submit;
              <br />
              (b) The accuracy of our Analyses depends entirely on the accuracy of the illustration provided;
              <br />
              (c) We do not independently verify any information contained in policy illustrations;
              <br />
              (d) Certain illustration formats or types may not be compatible with our Services;
              <br />
              (e) Processing errors or failures may occur due to document formatting or quality issues; and
              <br />
              (f) We are not responsible for any errors or omissions in the illustrations you provide.
            </p>
          </section>

          {/* Section 6 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-6">
              6. DATA RIGHTS AND PRIVACY
            </h2>
            <h3 className="text-xl font-medium mb-3">6.1 Data Collection and Use</h3>
            <p className="text-base mb-4">
              By using our Services, you acknowledge and agree that we may collect and process various types of data
              about you and your use of the Services. This data includes, without limitation: (a) account registration
              information; (b) policy illustration data; (c) usage data and analytics; (d) technical information about
              your devices and systems; (e) communications and correspondence; (f) payment information; and (g) any
              other information you provide to us through the Services.
            </p>

            <h3 className="text-xl font-medium mb-3">6.2 Data Rights and Licenses</h3>
            <p className="text-base mb-4">
              You represent and warrant that you have all necessary rights, permissions, and consents to provide any
              data you submit to our Services. You retain all ownership rights in your User Content but grant Financial
              Planner AI and its Affiliates a worldwide, non-exclusive, royalty-free, sublicensable, and transferable
              license to use, store, copy, modify, create derivative works from, distribute, publish, transmit, stream,
              broadcast, and otherwise exploit such User Content for any purpose related to providing and improving the
              Services.
            </p>

            <h3 className="text-xl font-medium mb-3">6.3 Privacy Practices</h3>
            <p className="text-base mb-4">
              Our collection, use, and disclosure of personal information is governed by our Privacy Policy. You
              acknowledge that you have reviewed our Privacy Policy and consent to the practices described therein.
            </p>

            <h3 className="text-xl font-medium mb-3">6.4 Data Security</h3>
            <p className="text-base mb-4">
              We implement reasonable technical, administrative, and physical security measures designed to protect your
              data from unauthorized access, disclosure, or misuse. However, no security measures are perfect or
              impenetrable.
            </p>

            <h3 className="text-xl font-medium mb-3">6.5 Data Retention and Deletion</h3>
            <p className="text-base mb-4">
              We retain your data for as long as necessary to provide the Services, comply with our legal obligations,
              resolve disputes, and enforce our agreements. Upon termination of your account, we may retain your data
              for a reasonable period of time for backup, archival, audit, or legal purposes.
            </p>
          </section>

          {/* Section 7 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-7">
              7. PAYMENT TERMS AND CONDITIONS
            </h2>
            <h3 className="text-xl font-medium mb-3">7.1 Fees and Payment</h3>
            <p className="text-base mb-4">
              Access to certain features of our Services requires payment of fees as specified on our Website or in a
              separate written agreement. All fees are quoted in U.S. dollars and are exclusive of applicable taxes.
            </p>

            <h3 className="text-xl font-medium mb-3">7.2 Subscription Terms</h3>
            <p className="text-base mb-4">
              Our Services may be offered on a subscription basis with recurring payments. By subscribing to our
              Services, you authorize us to charge your payment method on a recurring basis until you cancel your
              subscription.
            </p>

            <h3 className="text-xl font-medium mb-3">7.3 Payment Processing</h3>
            <p className="text-base mb-4">
              We use third-party payment processors to process payments for our Services. Your use of these payment
              services is subject to the applicable processor&apos;s terms of service and privacy policy.
            </p>

            <h3 className="text-xl font-medium mb-3">7.4 Late Payments and Collection</h3>
            <p className="text-base mb-4">
              Any amounts not paid when due shall bear interest at the rate of 1.5% per month or the maximum rate
              permitted by law, whichever is less.
            </p>

            <h3 className="text-xl font-medium mb-3">7.5 Taxes</h3>
            <p className="text-base mb-4">
              You are responsible for paying all taxes, levies, duties, and assessments of any kind imposed by any
              governmental authority in connection with your use of the Services, excluding taxes based on our net
              income.
            </p>
          </section>

          {/* Section 8 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-8">
              8. USAGE RESTRICTIONS AND REQUIREMENTS
            </h2>
            <h3 className="text-xl font-medium mb-3">8.1 Acceptable Use</h3>
            <p className="text-base mb-4">
              You agree to use the Services only for lawful purposes and in accordance with these Terms. You shall not
              use the Services in any manner that could damage, disable, overburden, or impair our servers or networks,
              or interfere with any other party&apos;s use and enjoyment of the Services.
            </p>

            <h3 className="text-xl font-medium mb-3">8.2 Prohibited Activities</h3>
            <p className="text-base mb-4">Without limiting the generality of the foregoing, you shall not:</p>
            <p className="text-base mb-4">
              (a) Use the Services to engage in any unlawful, fraudulent, deceptive, or manipulative activity;
              <br />
              (b) Attempt to circumvent, disable, or otherwise interfere with any security-related features;
              <br />
              (c) Use any robot, spider, crawler, scraper, or other automated means to access the Services;
              <br />
              (d) Copy, reproduce, distribute, modify, create derivative works of, publicly display, or sell any portion
              of the Services;
              <br />
              (e) Decompile, disassemble, or reverse engineer any part of the Services;
              <br />
              (f) Access the Services to build a similar or competitive product or service;
            </p>

            <h3 className="text-xl font-medium mb-3">8.3 Usage Monitoring and Enforcement</h3>
            <p className="text-base mb-4">We reserve the right to:</p>
            <p className="text-base mb-4">
              (a) Monitor and record all use of the Services for compliance with these Terms;
              <br />
              (b) Investigate any suspicious or reported violation of these Terms;
              <br />
              (c) Take appropriate legal action against anyone who violates these Terms;
              <br />
              (d) Remove or refuse any content that violates these Terms or may expose us to liability;
            </p>
          </section>

          {/* Section 9 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-9">
              9. INTELLECTUAL PROPERTY RIGHTS
            </h2>
            <h3 className="text-xl font-medium mb-3">9.1 Ownership of Services</h3>
            <p className="text-base mb-4">
              The Services, including all content, features, functionality, software, code, databases, user interfaces,
              algorithms, machine learning models, and documentation, are owned by Financial Planner AI and its
              licensors and are protected by United States and international intellectual property laws. These Terms
              don&apos;t grant you any rights to use any of our trademarks, logos, domain names, or other distinctive
              brand features except as expressly provided herein.
            </p>

            <h3 className="text-xl font-medium mb-3">9.2 Limited License Grant</h3>
            <p className="text-base mb-4">
              Subject to your compliance with these Terms and payment of applicable fees, Financial Planner AI grants
              you a limited, non-exclusive, non-transferable, non-sublicensable license to access and use the Services
              solely for your internal business or personal purposes.
            </p>

            <h3 className="text-xl font-medium mb-3">9.3 Restrictions on Use</h3>
            <p className="text-base mb-4">You shall not, and shall not permit any third party to:</p>
            <p className="text-base mb-4">
              (a) Copy, modify, translate, or create derivative works based on the Services;
              <br />
              (b) Sell, sublicense, transfer, lease, rent, loan, or otherwise distribute the Services;
              <br />
              (c) Reverse engineer, decompile, disassemble, or attempt to discover the source code;
              <br />
              (d) Remove, alter, or obscure any proprietary notices;
              <br />
              (e) Use the Services to develop any similar or competitive product;
              <br />
              (f) Use any unauthorized third-party software or tools to extract data.
            </p>

            <h3 className="text-xl font-medium mb-3">9.4 Feedback and Suggestions</h3>
            <p className="text-base mb-4">
              If you provide any feedback, suggestions, comments, ideas, or recommendations regarding the Services
              (&quot;Feedback&quot;), you hereby grant Financial Planner AI a worldwide, perpetual, irrevocable,
              royalty-free license to use and exploit such Feedback for any purpose without restriction or compensation.
            </p>
          </section>

          {/* Section 10 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-10">
              10. THIRD-PARTY SERVICES AND CONTENT
            </h2>
            <h3 className="text-xl font-medium mb-3">10.1 Third-Party Services</h3>
            <p className="text-base mb-4">
              The Services may contain links to integrate with, or enable access to third-party websites, services, or
              resources (&quot;Third-Party Services&quot;). Your access and use of Third-Party Services is governed
              solely by the terms and conditions of such Third-Party Services.
            </p>

            <h3 className="text-xl font-medium mb-3">10.2 Third-Party Content</h3>
            <p className="text-base mb-4">
              The Services may display, include, or make available content, data, information, applications, or
              materials from third parties (&quot;Third-Party Content&quot;). You acknowledge and agree that:
            </p>
            <p className="text-base mb-4">
              (a) We do not control, endorse, or adopt any Third-Party Content;
              <br />
              (b) We make no representations or warranties regarding Third-Party Content;
              <br />
              (c) We are not responsible for examining or evaluating the content, accuracy, completeness, availability,
              timeliness, validity, legality, quality, or any other aspect of Third-Party Content;
              <br />
              (d) We shall not be liable for any Third-Party Content, or any loss or damage caused by your use of or
              reliance on Third-Party Content.
            </p>
          </section>

          {/* Section 11 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-11">
              11. WARRANTIES AND DISCLAIMERS
            </h2>
            <h3 className="text-xl font-medium mb-3">11.1 Disclaimer of Warranties</h3>
            <p className="text-base mb-4">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND
              &quot;AS AVAILABLE,&quot; WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND. FINANCIAL PLANNER AI AND ITS
              LICENSORS EXPRESSLY DISCLAIM ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING
              WITHOUT LIMITATION:
            </p>
            <p className="text-base mb-4">
              (a) WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR
              NON-INFRINGEMENT;
              <br />
              (b) WARRANTIES ARISING OUT OF COURSE OF DEALING, USAGE, OR TRADE;
              <br />
              (c) WARRANTIES REGARDING THE SECURITY, RELIABILITY, TIMELINESS, OR PERFORMANCE OF THE SERVICES;
              <br />
              (d) WARRANTIES REGARDING THE ACCURACY OR COMPLETENESS OF ANY ANALYSES;
              <br />
              (e) WARRANTIES THAT THE SERVICES WILL MEET YOUR REQUIREMENTS OR BE UNINTERRUPTED;
              <br />
              (f) WARRANTIES REGARDING THE QUALITY, ACCURACY, OR RELIABILITY OF ANY INFORMATION.
            </p>
          </section>

          {/* Section 12 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-12">
              12. LIMITATION OF LIABILITY
            </h2>
            <h3 className="text-xl font-medium mb-3">12.1 Exclusion of Damages</h3>
            <p className="text-base mb-4">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL FINANCIAL PLANNER AI, ITS AFFILIATES,
              LICENSORS, OR SERVICE PROVIDERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE,
              OR EXEMPLARY DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION DAMAGES FOR:
            </p>
            <p className="text-base mb-4">
              (a) LOSS OF PROFITS, REVENUE, BUSINESS, OR ANTICIPATED SAVINGS;
              <br />
              (b) LOSS OF USE, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES;
              <br />
              (c) BUSINESS INTERRUPTION OR DIMINUTION IN VALUE;
              <br />
              (d) PERSONAL INJURY OR PROPERTY DAMAGE;
              <br />
              (e) ANY INVESTMENT, EXPENDITURE, OR COMMITMENT BY YOU;
              <br />
              (f) ANY ERRORS OR OMISSIONS IN ANY ANALYSIS OR OUTPUT;
              <br />
              (g) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS;
              <br />
              (h) ANY INTERRUPTION OR CESSATION OF TRANSMISSION;
              <br />
              (i) ANY BUGS, VIRUSES, OR OTHER HARMFUL CODE.
            </p>
          </section>

          {/* Section 13 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-13">
              13. DISPUTE RESOLUTION AND ARBITRATION
            </h2>
            <h3 className="text-xl font-medium mb-3">13.1 Agreement to Arbitrate</h3>
            <p className="text-base mb-4">
              PLEASE READ THIS SECTION CAREFULLY AS IT AFFECTS YOUR LEGAL RIGHTS AND PROVIDES FOR RESOLUTION OF DISPUTES
              THROUGH BINDING INDIVIDUAL ARBITRATION.
            </p>
            <p className="text-base mb-4">
              You and Financial Planner AI agree that any dispute, claim, or controversy arising out of or relating to
              these Terms, or your use of the Services (collectively, &quot;Disputes&quot;) will be resolved exclusively
              through binding individual arbitration rather than in court.
            </p>
          </section>

          {/* Section 14 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-14">
              14. INDEMNIFICATION
            </h2>
            <h3 className="text-xl font-medium mb-3">14.1 Indemnification Obligations</h3>
            <p className="text-base mb-4">
              You agree to defend, indemnify, and hold harmless Financial Planner AI, its Affiliates, licensors, and
              service providers, and their respective officers, directors, employees, contractors, agents, licensors,
              suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards,
              losses, costs, expenses, or fees (including reasonable attorneys&apos; fees) arising out of or relating to
              your violation of these Terms or use of the Services.
            </p>
          </section>

          {/* Section 15 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-15">
              15. TERM AND TERMINATION
            </h2>
            <h3 className="text-xl font-medium mb-3">15.1 Term</h3>
            <p className="text-base mb-4">
              These Terms commence on the date you first accept them and continue until terminated in accordance with
              their provisions.
            </p>
          </section>

          {/* Section 16 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-16">
              16. GENERAL PROVISIONS
            </h2>
            <h3 className="text-xl font-medium mb-3">16.1 Governing Law</h3>
            <p className="text-base mb-4">
              These Terms and any dispute arising out of or related to these Terms or the Services shall be governed by
              and construed in accordance with the laws of the State of New Jersey, without regard to its conflict of
              law principles.
            </p>
          </section>

          {/* Section 17 */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" id="section-17">
              17. CONTACT INFORMATION
            </h2>
            <h3 className="text-xl font-medium mb-3">17.1 General Inquiries</h3>
            <p className="text-base mb-4">
              For general inquiries about the Services or these Terms, please contact us at:
            </p>
            <p className="text-base mb-4">
              Financial Planner AI, LLC
              <br />
              <Link href="mailto:rpc@financialplanner-ai.com" className="text-primary hover:underline">
                rpc@financialplanner-ai.com
              </Link>
            </p>

            <h3 className="text-xl font-medium mb-3">17.2 Legal Notices</h3>
            <p className="text-base mb-4">For legal notices, please contact us at:</p>
            <p className="text-base mb-4">
              Financial Planner AI, LLC
              <br />
              Attn: Legal Matter
              <br />
              155 Glendale Drive
              <br />
              Freehold, NJ 07728
              <br />
              <Link href="mailto:rpc@financialplanner-ai.com" className="text-primary hover:underline">
                rpc@financialplanner-ai.com
              </Link>
            </p>
          </section>

          {/* Footer */}
          <div className="mt-12 border-t pt-8">
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">
                Last Updated: January 29, 2025
                <br />© 2025 Financial Planner AI, LLC. All rights reserved.
              </p>
            </div>
          </div>
        </article>
      </main>
    </div>
  )
}

