import React from "react"

interface Section {
  id: string
  title: string
}

interface TermsContentProps {
  sections: Section[]
}

export function TermsContent({ sections }: TermsContentProps) {
  return (
    <div className="space-y-8">
      <section id="important-notice">
        <h1 className="text-4xl font-bold mb-6">TERMS OF SERVICE</h1>
        <p className="font-semibold">Effective Date: January 1, 2025</p>
        <div className="bg-muted p-4 rounded-lg my-8">
          <p className="font-bold">IMPORTANT NOTICE REGARDING YOUR LEGAL RIGHTS</p>
          <p className="mt-2">
            {"PLEASE READ THESE TERMS OF SERVICE CAREFULLY. THEY CONTAIN AN ARBITRATION AGREEMENT AND CLASS ACTION WAIVER THAT AFFECT YOUR LEGAL RIGHTS."}
          </p>
        </div>
        <p>
          {"By accessing or using the Services provided by Financial Planner AI, LLC, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service, including the binding arbitration provision and class action waiver found in Section 12."}
        </p>
      </section>

      <section id="section-1" className="space-y-4">
        <h2 className="text-2xl font-bold">1. INTRODUCTION AND ACCEPTANCE</h2>
        <p>
          {"Welcome to Financial Planner AI. These Terms of Service (the \"Terms\") constitute a legally binding agreement between you and Financial Planner AI, LLC, a limited liability company organized under the laws of New Jersey (\"Financial Planner AI,\" \"we,\" \"our,\" or \"us\"). These Terms govern your access to and use of our website located at https://www.lifeinsuranceplanner-ai.com (the \"Website\"), our proprietary web-based software application (the \"Application\"), our AI-powered analysis feature (\"Insurance Planner AI\"), our chatbot service, and all related services (collectively, the \"Services\")."}
        </p>
        <p>
          {"These Terms incorporate by reference our Privacy Policy, available at https://www.lifeinsuranceplanner-ai.com/privacy, our Cookie Policy https://www.lifeinsuranceplanner-ai.com/cookie-policy and any additional terms, conditions, or policies we may provide to you from time to time. Together, these documents form the entire agreement between you and Financial Planner AI regarding your use of our Services."}
        </p>
        <p>
          {"By accessing or using our Services, you represent and warrant that you have read, understood, and agree to be bound by these Terms. If you don\\'t agree to these Terms in their entirety, you must not access or use our Services. If you are accessing or using our Services on behalf of a business entity, you represent and warrant that you have the authority to bind such entity to these Terms, and references to \"you\" and \"your\" in these Terms refer to both you individually and such entity."}
        </p>
      </section>

      <section id="section-2" className="space-y-4">
        <h2 className="text-2xl font-bold">2. DEFINITIONS AND INTERPRETATION</h2>
        <h3 className="text-xl font-semibold">2.1 Throughout these Terms, the following definitions apply:</h3>
        <div className="space-y-2">
          <p>
            {"\"Affiliate\" means any entity that directly or indirectly controls, is controlled by, or is under common control with Financial Planner AI, where \"control\" means the ownership of, or the power to vote, at least fifty percent (50%) of the voting stock, shares or interests of such entity."}
          </p>
          <p>
            {"\"AI Technology\" means our artificial intelligence and machine learning technologies, algorithms, models, and systems used to provide the Services."}
          </p>
          <p>
            {"\"Analyses\" means the outputs, reports, summaries, and other materials generated by our AI Technology based on the information and documentation you provide."}
          </p>
          <p>
            {"\"Confidential Information\" means any non-public information that relates to our business, technology, customers, or Services, including but not limited to our AI Technology, trade secrets, know-how, software code, technical specifications, development plans, and business strategies."}
          </p>
        </div>

        <h3 className="text-xl font-semibold">2.2 In these Terms:</h3>
        <div className="space-y-2">
          <p>
            {"(a) the words \"include,\" \"includes,\" and \"including\" are deemed to be followed by the words \"without limitation\";"}
            <br />
            {"(b) the word \"or\" is not exclusive;"}
            <br />
            {"(c) the words \"herein,\" \"hereof,\" \"hereby,\" \"hereto,\" and \"hereunder\" refer to these Terms as a whole; and"}
            <br />
            {"(d) words denoting the singular have a comparable meaning when used in the plural, and vice-versa."}
          </p>
        </div>
      </section>

      {/* Continue with Part 2 */}
      <section id="section-3" className="space-y-4">
        <h2 className="text-2xl font-bold">3. ELIGIBILITY AND REGISTRATION</h2>
        <h3 className="text-xl font-semibold">3.1 Eligibility Requirements</h3>
        <p>
          {"To access and use our Services, you must be at least eighteen (18) years old and have the legal capacity to form a binding contract with Financial Planner AI under applicable law. By using our Services, you represent and warrant that you meet these eligibility requirements. If you don\\'t meet these requirements, you must not access or use our Services."}
        </p>

        <h3 className="text-xl font-semibold">3.2 Registration Process</h3>
        <p>
          {"To access certain features of our Services, you must register for an account. When registering, you agree to provide accurate, current, and complete information about yourself as prompted by our registration process. You further agree to maintain and promptly update your registration information to keep it accurate, current, and complete. We reserve the right to suspend or terminate your account if we reasonably believe that any information you provide is inaccurate, outdated, or incomplete."}
        </p>

        <h3 className="text-xl font-semibold">3.3 Account Security</h3>
        <p>
          {"You are responsible for maintaining the confidentiality of your account credentials, including your username and password. You agree to notify us immediately of any unauthorized use of your account or any other breach of security. You acknowledge and agree that you are fully responsible for all activities that occur under your account. We reserve the right to suspend or terminate your account, deny your access to all or part of the Services, or delete any User Content you have provided, with or without notice, if we reasonably believe that you have violated these Terms or that your conduct may harm Financial Planner AI or its users."}
        </p>

        <h3 className="text-xl font-semibold">3.4 Account Types</h3>
        <p>
          {"Our Services may offer different types of accounts with varying features and functionality. The specific features and functionality available to you will depend on the type of account you register for and maintain. We reserve the right to modify, add, or remove features and functionality from any account type at any time in our sole discretion."}
        </p>
      </section>

      <section id="section-4" className="space-y-4">
        <h2 className="text-2xl font-bold">4. SERVICE DESCRIPTION AND SCOPE</h2>
        <h3 className="text-xl font-semibold">4.1 Core Services</h3>
        <p>
          {"Financial Planner AI provides a web-based software application that enables Life Insurance Policy Owners to conduct life insurance policy analyses through our proprietary AI Technology. Our core Services include: (a) automated analysis of life insurance policy illustrations; (b) generation of technical advisor reports; (c) creation of client-ready summaries; and (d) basic information delivery through our chatbot interface. The Services are designed to help Policy Owners better understand their life insurance policies and prepare for discussions with their Professional Advisors."}
        </p>

        <h3 className="text-xl font-semibold">4.2 Service Delivery</h3>
        <p>
          {"We will make the Services available to you pursuant to these Terms and any applicable Documentation. We may modify, enhance, or otherwise change the Services at any time in our sole discretion. We will use commercially reasonable efforts to provide the Services in accordance with industry standards, but we don\\'t guarantee that the Services will be provided without interruption or error-free. You acknowledge that our Services are subject to limitations, delays, and other problems inherent in the use of internet and electronic communications."}
        </p>

        <h3 className="text-xl font-semibold">4.3 Service Access</h3>
        <p>
          {"Subject to your compliance with these Terms and payment of applicable fees, we grant you a limited, non-exclusive, non-transferable, non-sublicensable right to access and use the Services solely for your internal business or personal purposes during the term of these Terms. This right is conditioned on your compliance with all applicable laws, regulations, and these Terms."}
        </p>
      </section>

      <section id="section-5" className="space-y-4">
        <h2 className="text-2xl font-bold">5. CRITICAL LIMITATIONS AND DISCLAIMERS</h2>
        <h3 className="text-xl font-semibold">5.1 No Professional Advice</h3>
        <p>
          {"YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT THE SERVICES DO NOT CONSTITUTE PROFESSIONAL ADVICE OF ANY KIND. The Services are informational tools only and are not intended to replace the advice or services of licensed professionals. Financial Planner AI does not provide tax, legal, financial, insurance, or investment advice. We do not recommend, endorse, or sell any insurance products, policies, or companies."}
        </p>
        <p>
          {"You must consult with qualified Professional Advisors before making any decisions about your life insurance policy or taking any actions based on information provided through our Services. The Analyses generated by our Services are intended solely as starting points for discussions with your Professional Advisors and should never be relied upon as the sole basis for any decision or action regarding your life insurance policy."}
        </p>

        <h3 className="text-xl font-semibold">5.2 AI Technology Limitations</h3>
        <p>
          {"You expressly acknowledge and understand that our Services utilize automated artificial intelligence and machine learning technologies that have inherent limitations and potential for error. The accuracy and reliability of our Analyses depend entirely on the quality, completeness, and accuracy of the information and documentation you provide. Different illustration dates, assumptions, or inputs may produce materially different analysis results."}
        </p>
        <p>{"Our AI Technology:"}</p>
        <div className="space-y-2 pl-4">
          <p>{"(a) May contain errors, bugs, or inaccuracies;"}</p>
          <p>{"(b) May not capture all relevant factors or considerations;"}</p>
          <p>{"(c) May produce inconsistent or unexpected results;"}</p>
          <p>{"(d) Requires human review and professional verification;"}</p>
          <p>{"(e) Is subject to regular updates that may affect results;"}</p>
          <p>{"(f) Cannot verify the completeness or accuracy of input data;"}</p>
          <p>{"(g) May have biases or limitations we have not identified; and"}</p>
          <p>{"(h) Should never be relied upon without independent verification."}</p>
        </div>

        <h3 className="text-xl font-semibold">5.3 Document Processing Restrictions</h3>
        <p>
          {"The Services are designed to process only life insurance policy illustrations. We do not analyze other insurance or financial documents. You acknowledge and agree that:"}
        </p>
        <div className="space-y-2 pl-4">
          <p>{"(a) We cannot verify the completeness, accuracy, or authenticity of any illustration you submit;"}</p>
          <p>{"(b) The accuracy of our Analyses depends entirely on the accuracy of the illustration provided;"}</p>
          <p>{"(c) We do not independently verify any information contained in policy illustrations;"}</p>
          <p>{"(d) Certain illustration formats or types may not be compatible with our Services;"}</p>
          <p>{"(e) Processing errors or failures may occur due to document formatting or quality issues; and"}</p>
          <p>{"(f) We are not responsible for any errors or omissions in the illustrations you provide."}</p>
        </div>

        <h3 className="text-xl font-semibold">5.4 No Guarantee of Results</h3>
        <p>
          {"We make no representations or warranties about the accuracy, reliability, completeness, quality, or timeliness of any Analysis, output, or result produced by our Services. You acknowledge that the Services are provided for informational purposes only, and we do not guarantee that:"}
        </p>
        <div className="space-y-2 pl-4">
          <p>{"(a) The Services will meet your specific requirements or expectations;"}</p>
          <p>{"(b) The Analyses will be accurate, complete, or useful for your purposes;"}</p>
          <p>{"(c) Any particular results or outcomes will be achieved through use of the Services;"}</p>
          <p>{"(d) The Services will be compatible with your existing systems or processes;"}</p>
          <p>{"(e) The Services will operate without interruption or be error-free; or"}</p>
          <p>{"(f) All errors or defects in the Services will be corrected."}</p>
        </div>

        <h3 className="text-xl font-semibold">5.5 Compliance with Laws</h3>
        <p>
          {"You are solely responsible for ensuring that your use of the Services complies with all applicable laws, regulations, and professional obligations. We do not represent or warrant that the Services are appropriate or available for use in any particular jurisdiction. If you choose to access or use the Services, you do so at your own risk and are responsible for complying with all local laws, regulations, and professional requirements."}
        </p>

        <h3 className="text-xl font-semibold">5.6 Changes and Updates</h3>
        <p>
          {"We reserve the right to make changes to the Services at any time and without notice. These changes may include:"}
        </p>
        <div className="space-y-2 pl-4">
          <p>{"(a) Adding or removing features or functionality;"}</p>
          <p>{"(b) Updating our AI Technology or algorithms;"}</p>
          <p>{"(c) Modifying user interfaces or experiences;"}</p>
          <p>{"(d) Changing technical specifications or requirements;"}</p>
          <p>{"(e) Updating security measures or protocols;"}</p>
          <p>{"(f) Modifying documentation or support materials; and"}</p>
          <p>{"(g) Making any other changes we deem necessary or appropriate."}</p>
        </div>
        <p>
          {"We are not liable to you or any third party for any modification, suspension, or discontinuation of any part of the Services. Your continued use of the Services following any changes constitutes your acceptance of such changes."}
        </p>

        <h3 className="text-xl font-semibold">5.7 Support and Maintenance</h3>
        <p>
          {"While we strive to maintain the quality and availability of our Services, we do not guarantee any particular level of uptime or availability. We may perform scheduled or emergency maintenance on the Services at any time. During such maintenance periods, the Services may be unavailable or operate with limited functionality. We will use commercially reasonable efforts to minimize any disruption to the Services, but we are not liable for any damages or losses resulting from such maintenance or unavailability."}
        </p>
      </section>

      <section id="section-6" className="space-y-4">
        <h2 className="text-2xl font-bold">6. DATA RIGHTS AND PRIVACY</h2>
        <h3 className="text-xl font-semibold">6.1 Data Collection and Use</h3>
        <p>
          {"By using our Services, you acknowledge and agree that we may collect and process various types of data about you and your use of the Services. This data includes, without limitation: (a) account registration information; (b) policy illustration data; (c) usage data and analytics; (d) technical information about your devices and systems; (e) communications and correspondence; (f) payment information; and (g) any other information you provide to us through the Services. You hereby grant Financial Planner AI a worldwide, perpetual, irrevocable, royalty-free license to use, copy, modify, create derivative works from, distribute, perform, display, and otherwise exploit such data for the purposes of: (i) providing and improving the Services; (ii) developing and training our AI Technology; (iii) generating aggregated analytics and insights; (iv) preventing fraud and abuse; (v) complying with legal obligations; and (vi) any other purpose disclosed to you at the time of collection."}
        </p>

        <h3 className="text-xl font-semibold">6.2 Data Rights and Licenses</h3>
        <p>
          {"You represent and warrant that you have all necessary rights, permissions, and consents to provide any data you submit to our Services. You retain all ownership rights in your User Content but grant Financial Planner AI and its Affiliates a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, store, copy, modify, create derivative works from, distribute, publish, transmit, stream, broadcast, and otherwise exploit such User Content for any purpose related to providing and improving the Services. You also grant Financial Planner AI and its Affiliates the right to use your name, likeness, and other identifying information in connection with your User Content."}
        </p>

        <h3 className="text-xl font-semibold">6.3 Privacy Practices</h3>
        <p>
          {"Our collection, use, and disclosure of personal information is governed by our Privacy Policy, available at https://www.lifeinsuranceplanner-ai.com/privacy. You acknowledge that you have reviewed our Privacy Policy and consent to the practices described therein. We reserve the right to update our Privacy Policy at any time in accordance with its terms. Your continued use of the Services following any changes to our Privacy Policy constitutes acceptance of such changes."}
        </p>

        <h3 className="text-xl font-semibold">6.4 Data Security</h3>
        <p>
          {"We implement reasonable technical, administrative, and physical security measures designed to protect your data from unauthorized access, disclosure, or misuse. However, no security measures are perfect or impenetrable. You acknowledge that: (a) any security measures can be circumvented; (b) we cannot guarantee the absolute security of any data; (c) transmissions over the internet are never completely secure; and (d) we are not responsible for the circumvention of any privacy settings or security measures contained in the Services."}
        </p>

        <h3 className="text-xl font-semibold">6.5 Data Retention and Deletion</h3>
        <p>
          {"We retain your data for as long as necessary to provide the Services, comply with our legal obligations, resolve disputes, and enforce our agreements. Upon termination of your account, we may retain your data for a reasonable period of time for backup, archival, audit, or legal purposes. You may request deletion of your account and associated data by contacting us at rpc@financialplanner-ai.com. However, some information may be retained indefinitely in our backup systems or as required by law."}
        </p>
      </section>

      {/* Continue with Part 3 */}
      <section id="section-7" className="space-y-4">
        <h2 className="text-2xl font-bold">7. PAYMENT TERMS AND CONDITIONS</h2>
        <h3 className="text-xl font-semibold">7.1 Fees and Payment</h3>
        <p>
          {"Access to certain features of our Services requires payment of fees as specified on our Website or in a separate written agreement. All fees are quoted in U.S. dollars and are exclusive of applicable taxes. You agree to pay all fees and applicable taxes in accordance with the payment terms presented to you at the time of purchase. You authorize us to charge your designated payment method for all fees and taxes due. Fees paid are non-refundable except as expressly provided in these Terms or required by law."}
        </p>

        <h3 className="text-xl font-semibold">7.2 Subscription Terms</h3>
        <p>
          {"Our Services may be offered on a subscription basis with recurring payments. By subscribing to our Services, you authorize us to charge your payment method on a recurring basis until you cancel your subscription. Subscription fees will be billed at the beginning of each subscription period. You acknowledge that your subscription will automatically renew unless you cancel it prior to the renewal date. We reserve the right to change subscription fees upon notice to you. If you don\\'t accept a fee change, you must cancel your subscription before the change takes effect."}
        </p>

        <h3 className="text-xl font-semibold">7.3 Payment Processing</h3>
        <p>
          {"We use third-party payment processors to process payments for our Services. Your use of these payment services is subject to the applicable processor\\'s terms of service and privacy policy. We are not responsible for any errors, failures, or interruptions in payment processing. You agree to provide accurate and complete payment information and to update such information as necessary. We reserve the right to suspend or terminate your access to paid features if your payment method is declined or expires."}
        </p>

        <h3 className="text-xl font-semibold">7.4 Late Payments and Collection</h3>
        <p>
          {"Any amounts not paid when due shall bear interest at the rate of 1.5% per month or the maximum rate permitted by law, whichever is less. You agree to reimburse us for all costs and expenses incurred in collecting past due amounts, including reasonable attorneys\\' fees. We may suspend or terminate your access to paid features if your account becomes delinquent and you fail to cure such delinquency within thirty (30) days after notice."}
        </p>

        <h3 className="text-xl font-semibold">7.5 Taxes</h3>
        <p>
          {"You are responsible for paying all taxes, levies, duties, and assessments of any kind imposed by any governmental authority in connection with your use of the Services, excluding taxes based on our net income. If we have a legal obligation to pay or collect taxes for which you are responsible, you authorize us to charge your payment method for such amounts."}
        </p>

        <h3 className="text-xl font-semibold">7.6 Billing Disputes</h3>
        <p>
          {"You must notify us of any billing disputes within sixty (60) days after the charge appears on your payment method statement. After such period, you waive any right to dispute such charges. All billing disputes must be sent in writing to rpc@financialplanner-ai.com and must include detailed information about the nature of the dispute. We will make good faith efforts to resolve billing disputes promptly but reserve the right to make final determinations regarding any disputed charges."}
        </p>

        <h3 className="text-xl font-semibold">7.7 Free Trials and Promotions</h3>
        <p>
          {"We may offer free trials or promotional rates for certain features of our Services. Such offers are subject to the specific terms presented at the time of the offer. Unless otherwise specified, free trials will automatically convert to paid subscriptions at the end of the trial period unless cancelled before the trial ends. You authorize us to charge your payment method at the end of the free trial unless you cancel prior to its expiration."}
        </p>
      </section>

      <section id="section-8" className="space-y-4">
        <h2 className="text-2xl font-bold">8. USAGE RESTRICTIONS AND REQUIREMENTS</h2>
        <h3 className="text-xl font-semibold">8.1 Acceptable Use</h3>
        <p>
          {"You agree to use the Services only for lawful purposes and in accordance with these Terms. You shall not use the Services in any manner that could damage, disable, overburden, or impair our servers or networks, or interfere with any other party\\'s use and enjoyment of the Services. You acknowledge and agree that we may monitor your use of the Services to ensure compliance with these Terms and to protect our rights and interests."}
        </p>

        <h3 className="text-xl font-semibold">8.2 Prohibited Activities</h3>
        <p>{"Without limiting the generality of the foregoing, you shall not:"}</p>
        <div className="space-y-2 pl-4">
          <p>{"(a) Use the Services to engage in any unlawful, fraudulent, deceptive, or manipulative activity;"}</p>
          <p>{"(b) Attempt to circumvent, disable, or otherwise interfere with any security-related features of the Services or features that prevent or restrict use or copying of any content;"}</p>
          <p>{"(c) Use any robot, spider, crawler, scraper, or other automated means to access the Services or collect information from the Services;"}</p>
          <p>{"(d) Copy, reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, transmit, sell, rent, lease, lend, or sublicense any portion of the Services;"}</p>
          <p>{"(e) Decompile, disassemble, reverse engineer, or attempt to discover any source code, object code, or underlying ideas or algorithms of the Services;"}</p>
          <p>{"(f) Access the Services to build a similar or competitive product or service;"}</p>
          <p>{"(g) Upload, transmit, or distribute any computer viruses, worms, malicious code, or any software intended to damage or alter a computer system or data;"}</p>
          <p>{"(h) Use the Services to send unsolicited communications, promotions, advertisements, or spam;"}</p>
          <p>{"(i) Submit false or misleading information or impersonate another person or entity;"}</p>
          <p>{"(j) Violate, misappropriate, or infringe any intellectual property, publicity, privacy, or other rights of any party;"}</p>
          <p>{"(k) Use the Services in any manner that could interfere with, disrupt, negatively affect, or inhibit other users from fully enjoying the Services."}</p>
        </div>

        <h3 className="text-xl font-semibold">8.3 Usage Monitoring and Enforcement</h3>
        <p>{"We reserve the right to:"}</p>
        <div className="space-y-2 pl-4">
          <p>{"(a) Monitor and record all use of the Services for compliance with these Terms;"}</p>
          <p>{"(b) Investigate any suspicious or reported violation of these Terms;"}</p>
          <p>{"(c) Take appropriate legal action against anyone who violates these Terms;"}</p>
          <p>{"(d) Remove or refuse any content that violates these Terms or may expose us to liability;"}</p>
          <p>{"(e) Terminate or suspend your access to the Services for violations of these Terms;"}</p>
          <p>{"(f) Report any activity we suspect violates any law or regulation to appropriate authorities."}</p>
        </div>
      </section>

      <section id="section-9" className="space-y-4">
        <h2 className="text-2xl font-bold">9. INTELLECTUAL PROPERTY RIGHTS</h2>
        <h3 className="text-xl font-semibold">9.1 Ownership of Services</h3>
        <p>
          {"The Services, including all content, features, functionality, software, code, databases, user interfaces, algorithms, machine learning models, and documentation, are owned by Financial Planner AI and its licensors and are protected by United States and international intellectual property laws. These Terms don\\'t grant you any rights to use any of our trademarks, logos, domain names, or other distinctive brand features except as expressly provided herein."}
        </p>

        <h3 className="text-xl font-semibold">9.2 Limited License Grant</h3>
        <p>
          {"Subject to your compliance with these Terms and payment of applicable fees, Financial Planner AI grants you a limited, non-exclusive, non-transferable, non-sublicensable license to access and use the Services solely for your internal business or personal purposes. This license is conditional upon your continued compliance with these Terms and will terminate automatically upon any breach of these Terms by you or upon termination of your account."}
        </p>

        <h3 className="text-xl font-semibold">9.3 Restrictions on Use</h3>
        <p>{"You shall not, and shall not permit any third party to:"}</p>
        <div className="space-y-2 pl-4">
          <p>{"(a) Copy, modify, translate, or create derivative works based on the Services;"}</p>
          <p>{"(b) Sell, sublicense, transfer, lease, rent, loan, or otherwise distribute the Services to any third party;"}</p>
          <p>{"(c) Reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code, or underlying structure of the Services;"}</p>
          <p>{"(d) Remove, alter, or obscure any proprietary notices in or on the Services;"}</p>
          <p>{"(e) Use the Services to develop any similar or competitive product or service;"}</p>
          <p>{"(f) Use any unauthorized third-party software or tools designed to extract data or content from the Services."}</p>
        </div>

        <h3 className="text-xl font-semibold">9.4 Feedback and Suggestions</h3>
        <p>
          {"If you provide any feedback, suggestions, comments, ideas, or recommendations regarding the Services (\"Feedback\"), you hereby grant Financial Planner AI a worldwide, perpetual, irrevocable, royalty-free license to use, incorporate, modify, display, perform, create derivative works from, and otherwise exploit such Feedback for any purpose without restriction or compensation to you."}
        </p>
      </section>

      {/* Continue with Part 4 */}
      <section id="section-10" className="space-y-4">
        <h2 className="text-2xl font-bold">10. THIRD-PARTY SERVICES AND CONTENT</h2>
        <h3 className="text-xl font-semibold">10.1 Third-Party Services</h3>
        <p>
          {"The Services may contain links to integrate with, or enable access to third-party websites, services, or resources (\"Third-Party Services\"). Your access and use of Third-Party Services is governed solely by the terms and conditions of such Third-Party Services. Financial Planner AI does not endorse, is not responsible for, and makes no representations or warranties regarding any Third-Party Services, including their accuracy, completeness, timeliness, validity, legality, quality, or any other aspect thereof."}
        </p>

        <h3 className="text-xl font-semibold">10.2 Third-Party Content</h3>
        <p>
          {"The Services may display, include, or make available content, data, information, applications, or materials from third parties (\"Third-Party Content\"). You acknowledge and agree that:"}
        </p>
        <div className="space-y-2 pl-4">
          <p>{"(a) We do not control, endorse, or adopt any Third-Party Content;"}</p>
          <p>{"(b) We make no representations or warranties regarding Third-Party Content;"}</p>
          <p>{"(c) We are not responsible for examining or evaluating the content, accuracy, completeness, availability, timeliness, validity, legality, quality, or any other aspect of Third-Party Content;"}</p>
          <p>{"(d) We shall not be liable for any Third-Party Content, or any loss or damage caused by your use of or reliance on Third-Party Content."}</p>
        </div>

        <h3 className="text-xl font-semibold">10.3 Integration Partners</h3>
        <p>{"We may partner with third parties to provide certain features or functionality within the Services. These integration partners may have their own terms of service, privacy policies, and other agreements governing your use of their services. You acknowledge that:"}</p>
        <div className="space-y-2 pl-4">
          <p>{"(a) Your use of integration partner services is subject to their respective terms and policies;"}</p>
          <p>{"(b) We are not responsible for the performance, security, or availability of integration partner services;"}</p>
          <p>{"(c) Integration partners may access, collect, and use your data according to their terms and policies;"}</p>
          <p>{"(d) We may share your information with integration partners as necessary to provide the Services;"}</p>
          <p>{"(e) We reserve the right to modify, suspend, or discontinue any integration partner services at any time."}</p>
        </div>

        <h3 className="text-xl font-semibold">10.4 APIs and Developer Tools</h3>
        <p>{"If we provide you with access to any APIs, software development kits, or other developer tools, your use of such tools is subject to any additional terms and conditions we may provide. You agree to:"}</p>
        <div className="space-y-2 pl-4">
          <p>{"(a) Use developer tools only as expressly permitted;"}</p>
          <p>{"(b) Comply with all documentation and restrictions we provide;"}</p>
          <p>{"(c) Maintain the security and confidentiality of any API credentials;"}</p>
          <p>{"(d) Not exceed any rate limits or other usage restrictions;"}</p>
          <p>{"(e) Not use developer tools in any manner that could harm or impair the Services."}</p>
        </div>
      </section>

      <section id="section-11" className="space-y-4">
        <h2 className="text-2xl font-bold">11. WARRANTIES AND DISCLAIMERS</h2>
        <h3 className="text-xl font-semibold">11.1 Disclaimer of Warranties</h3>
        <p className="font-bold">
          {"TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES ARE PROVIDED \"AS IS\" AND \"AS AVAILABLE,\" WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND. FINANCIAL PLANNER AI AND ITS LICENSORS EXPRESSLY DISCLAIM ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING WITHOUT LIMITATION:"}
        </p>
        <div className="space-y-2 pl-4">
          <p>{"(a) WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT;"}</p>
          <p>{"(b) WARRANTIES ARISING OUT OF COURSE OF DEALING, USAGE, OR TRADE;"}</p>
          <p>{"(c) WARRANTIES REGARDING THE SECURITY, RELIABILITY, TIMELINESS, OR PERFORMANCE OF THE SERVICES;"}</p>
          <p>{"(d) WARRANTIES REGARDING THE ACCURACY OR COMPLETENESS OF ANY ANALYSES, OUTPUTS, OR RESULTS GENERATED BY THE SERVICES;"}</p>
          <p>{"(e) WARRANTIES THAT THE SERVICES WILL MEET YOUR REQUIREMENTS OR BE UNINTERRUPTED, ERROR-FREE, OR FREE FROM HARMFUL COMPONENTS;"}</p>
          <p>{"(f) WARRANTIES REGARDING THE QUALITY, ACCURACY, OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE SERVICES."}</p>
        </div>

        <h3 className="text-xl font-semibold">11.2 AI Technology Disclaimers</h3>
        <p>{"You expressly acknowledge and agree that:"}</p>
        <div className="space-y-2 pl-4">
          <p>{"(a) Our AI Technology is experimental and evolving technology that may produce errors, inaccuracies, or unexpected results;"}</p>
          <p>{"(b) The Analyses generated by our AI Technology are provided for informational purposes only and should not be relied upon without independent verification;"}</p>
          <p>{"(c) We do not warrant or guarantee the accuracy, completeness, timeliness, reliability, suitability, or usefulness of any Analysis or output generated by our AI Technology;"}</p>
          <p>{"(d) The AI Technology may be subject to limitations, delays, and other problems inherent in machine learning and artificial intelligence technologies;"}</p>
          <p>{"(e) We are not responsible for any decisions, actions, or consequences resulting from your use of or reliance upon any Analysis or output generated by our AI Technology."}</p>
        </div>

        <h3 className="text-xl font-semibold">11.3 Professional Services Disclaimers</h3>
        <p>{"You expressly acknowledge and agree that:"}</p>
        <div className="space-y-2 pl-4">
          <p>{"(a) The Services do not constitute professional financial, legal, tax, insurance, or investment advice;"}</p>
          <p>{"(b) We do not act as fiduciaries or advisors in providing the Services;"}</p>
          <p>{"(c) No information or Analysis provided through the Services should be considered a recommendation or endorsement;"}</p>
          <p>{"(d) You must consult with qualified professional advisors before making any decisions about your life insurance policy or financial matters;"}</p>
          <p>{"(e) We are not responsible for any decisions or actions you take based on information obtained through the Services."}</p>
        </div>
      </section>

      <section id="section-12" className="space-y-4">
        <h2 className="text-2xl font-bold">12. LIMITATION OF LIABILITY</h2>
        <h3 className="text-xl font-semibold">12.1 Exclusion of Damages</h3>
        <p className="font-bold">
          {"TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL FINANCIAL PLANNER AI, ITS AFFILIATES, LICENSORS, OR SERVICE PROVIDERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION DAMAGES FOR:"}
        </p>
        <div className="space-y-2 pl-4">
          <p>{"(a) LOSS OF PROFITS, REVENUE, BUSINESS, OR ANTICIPATED SAVINGS;"}</p>
          <p>{"(b) LOSS OF USE, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES;"}</p>
          <p>{"(c) BUSINESS INTERRUPTION OR DIMINUTION IN VALUE;"}</p>
          <p>{"(d) PERSONAL INJURY OR PROPERTY DAMAGE;"}</p>
          <p>{"(e) ANY INVESTMENT, EXPENDITURE, OR COMMITMENT BY YOU IN RELATION TO THESE TERMS OR YOUR USE OF THE SERVICES;"}</p>
          <p>{"(f) ANY ERRORS OR OMISSIONS IN ANY ANALYSIS OR OUTPUT;"}</p>
          <p>{"(g) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS OR ANY PERSONAL INFORMATION;"}</p>
          <p>{"(h) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES;"}</p>
          <p>{"(i) ANY BUGS, VIRUSES, OR OTHER HARMFUL CODE THAT MAY BE TRANSMITTED THROUGH THE SERVICES."}</p>
        </div>

        <h3 className="text-xl font-semibold">12.2 Liability Cap</h3>
        <p className="font-bold">
          {"TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, OUR AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICES, WHETHER IN CONTRACT, TORT, OR OTHERWISE, SHALL NOT EXCEED THE AMOUNT YOU PAID US FOR THE SERVICES DURING THE TWELVE (12) MONTHS PRECEDING THE CLAIM OR ONE HUNDRED DOLLARS ($100), WHICHEVER IS GREATER."}
        </p>

        <h3 className="text-xl font-semibold">12.3 Basis of Bargain</h3>
        <p>
          {"The limitations of damages and liability set forth above are fundamental elements of the basis of the bargain between Financial Planner AI and you. The Services would not be provided without such limitations, and you agree that the limitations and exclusions of liability, disclaimers, and exclusive remedies specified herein will survive even if found to have failed of their essential purpose."}
        </p>
      </section>

      <section id="section-13" className="space-y-4">
        <h2 className="text-2xl font-bold">13. DISPUTE RESOLUTION AND ARBITRATION</h2>
        <h3 className="text-xl font-semibold">13.1 Agreement to Arbitrate</h3>
        <p className="font-bold">
          {"PLEASE READ THIS SECTION CAREFULLY AS IT AFFECTS YOUR LEGAL RIGHTS AND PROVIDES FOR RESOLUTION OF DISPUTES THROUGH BINDING INDIVIDUAL ARBITRATION."}
        </p>
        <p>
          {"You and Financial Planner AI agree that any dispute, claim, or controversy arising out of or relating to these Terms or your use of the Services (collectively, \"Disputes\") will be resolved exclusively through binding individual arbitration rather than in court, except that:"}
        </p>
        <div className="space-y-2 pl-4">
          <p>{"(a) Each party retains the right to bring an individual action in small claims court;"}</p>
          <p>{"(b) Each party retains the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of intellectual property rights;"}</p>
          <p>{"(c) Each party retains the right to bring claims that are expressly excluded from arbitration by applicable law."}</p>
        </div>
      </section>

      <section id="section-14" className="space-y-4">
        <h2 className="text-2xl font-bold">14. INDEMNIFICATION</h2>
        <h3 className="text-xl font-semibold">14.1 Indemnification Obligations</h3>
        <p>
          {"You agree to defend, indemnify, and hold harmless Financial Planner AI, its Affiliates, licensors, and service providers, and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys\\' fees) arising out of or relating to your violation of these Terms or use of the Services."}
        </p>
      </section>

      <section id="section-15" className="space-y-4">
        <h2 className="text-2xl font-bold">15. TERM AND TERMINATION</h2>
        <h3 className="text-xl font-semibold">15.1 Term</h3>
        <p>
          {"These Terms commence on the date you first accept them and continue until terminated in accordance with their provisions."}
        </p>
      </section>

      <section id="section-16" className="space-y-4">
        <h2 className="text-2xl font-bold">16. GENERAL PROVISIONS</h2>
        <h3 className="text-xl font-semibold">16.1 Governing Law</h3>
        <p>
          {"These Terms and any dispute arising out of or related to these Terms or the Services shall be governed by and construed in accordance with the laws of the State of New Jersey, without regard to its conflict of law principles."}
        </p>
      </section>

      <section id="section-17" className="space-y-4">
        <h2 className="text-2xl font-bold">17. CONTACT INFORMATION</h2>
        <h3 className="text-xl font-semibold">17.1 General Inquiries</h3>
        <p>
          {"For general inquiries about the Services or these Terms, please contact us at:"}
        </p>
        <p>
          {"Financial Planner AI, LLC"}
          <br />
          {"Email: rpc@financialplanner-ai.com"}
        </p>

        <h3 className="text-xl font-semibold">17.2 Legal Notices</h3>
        <p>
          {"For legal notices, please contact us at:"}
        </p>
        <p>
          {"Financial Planner AI, LLC"}
          <br />
          {"Attn: Legal Matter"}
          <br />
          {"155 Glendale Drive"}
          <br />
          {"Freehold, NJ 07728"}
          <br />
          {"Email: rpc@financialplanner-ai.com"}
        </p>
      </section>

      <footer className="pt-8 border-t">
        <p className="text-sm text-muted-foreground">
          {"Last Updated: January 29, 2025"}
          <br />
          {"© 2025 Financial Planner AI, LLC. All rights reserved."}
        </p>
      </footer>
